# Generated by Django 2.0.7 on 2018-07-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180718_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
